### PR TITLE
Added LG Retro Gaming APK 

### PR DESCRIPTION
**Pull request by GTgyani206**
#55

### CODE REVIEW

**Comment by GTgyani206** [comment]
Don't merge this now I recently found that the apk is showing invalid for some devices... I'll fix it and then let @yashrajbharti  you know ...

**Comment by yashrajbharti** [comment]
Always convert PRs to draft in such cases

**Comment by yashrajbharti** [comment]
The repo can have outdated code. Best you can do is leave an open issue.

Here you can send the fixed app. Make this PR from draft PR to active and I'll review.

**Comment by yashrajbharti** [comment]
The repo can have outdated code. Best you can do is leave an open issue.

Here you can send the fixed app. Make this PR from draft PR to active and I'll review.

**Comment by yashrajbharti** [comment]
if any problems still exist, feel free to make a new PR

**Pull request merged**
